### ISSUE TITLE
Library installation for python

### ISSUE THREAD

**Issue by nikmihale** [ggsimao/tcc_mahalanobis#1]
Hello @ggsimao. 
I stumbled upon your repository while implementing my version of Polynomial Mahalanobis Distance and found it quite helpful. However, I was not able to build this project. I see this library was finished in  #3dea8 and later you committed a new installation for python, but I can't achieve this result. 
Could you help me with the required steps to use this library in python?

**Comment by ggsimao** [comment]
Check the instructions at https://codigos.ufsc.br/lapix/libmahala (it's the new, official repo for the library). If that doesn't help, can you send a bit more info here about what happened?

**Comment by nikmihale** [comment]
I keep having `fatal error: 'numpy/ndarrayobject.h' file not found`, none of numerous solutions online gave any result by far. I'm still trying to find a solution, but apparently having MacOS makes it more complicated than I expected

**Comment by ggsimao** [comment]
Just a hunch, but what Python version are you using? The CMake file looks for the 3.8.0 version, so if you're using another changing that to the one you have might solve the problem.

If that doesn't work, try checking this: https://stackoverflow.com/questions/24174394/cmake-is-not-able-to-find-python-libraries.

**Comment by nikmihale** [comment]
I tried creating a virtual environment with 3.8.0 and numerous other tricks from the link and related questions on stackoverflow. Finally managed to build the library, `python3 -c 'import libmahalapy'` seems to be working too. Apparently, case closed. Thank you.
